[package]
name = "rs-common"
version = "0.1.0"
authors = ["qorzj <zhangji@parsec.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
